doc: Updated examples to use the new disks syntax
Telmate/terraform-provider-proxmox pull request #948
Opened 2024-02-26 17:38 UTC by hestiahacker

This closes #932

2024-03-13 20:48 UTC, Tinyblargon requested changes

2024-03-13 20:48 UTC, Tinyblargon commented on docs/resources/cloud_init_disk.md
> +        disk {
With the new disk schema it should be like this:

```hcl
cd {
  iso = "${local.iso_storage_pool}:${proxmox_cloud_init_disk.ci.id}
}
```

Not 100% sure what `local.iso_storage_pool` and `proxmox_cloud_init_disk.ci.id` are in this situation.

2024-03-18 17:00 UTC, hestiahacker commented
Thanks for the review and correction. I think it should be good to go now

2024-04-11 15:11 UTC, TAAGECH9 commented
@Tinyblargon , do you think this PR could be merged 😄? I was struggling on my own with exactly the same issue and wanted to create a PR and then realized that there is already this PR open.

2024-04-11 15:15 UTC, merged

2024-04-11 15:46 UTC, TAAGECH9 commented
@Tinyblargon ,that was quick 🔥. Thank you very much ❤️